DSEDFinalProjectTripPlanner/Models/Human.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DSEDFinalProjectTripPlanner.Models
{
    public class Human
    {
        // represent the Passenger information
        [Required]
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string FrequentFlyerNumber { get; set; }
        public string TicketNumber { get; set; }
        public int TripId { get; set; }
        public int FlightId { get; set; }
        public int LodgingId { get; set; }
        public int OtherTransportationId { get; set; }
        public int RestaurantId { get; set; }
        public int CarRentalId { get; set; }
        public int ActivityTaskId { get; set; }
    }
}

DSEDFinalProjectTripPlanner/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DSEDFinalProjectTripPlanner.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DSEDFinalProjectTripPlanner.Data;
using DSEDFinalProjectTripPlanner.DTO;
using DSEDFinalProjectTripPlanner.Models;
using Microsoft.AspNetCore.Authorization;

namespace DSEDFinalProjectTripPlanner.Controllers
{
    [Authorize]
    public class FlightsController : Controller
    {
        private readonly Data.TripContext _context;

        public FlightsController(Data.TripContext context)
        {
            _context = context;
        }

        // GET: Flights
        public async Task<IActionResult> Index()
        {
            return View(await _context.Flights.ToListAsync());

            //return View(db.News.OrderByDescending(news => new.dateCreated).Take(10).ToList());
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .SingleOrDefaultAsync(m => m.Id == id);

            TripDTO _tfDto = new TripDTO();
            MyFlights _flights = new MyFlights();

            DatabaseManager.FlightId = (int)id;
            DatabaseManager.LodgingId = 0;
            DatabaseManager.OtherTransportationId = 0;
            DatabaseManager.RestaurantId = 0;
            DatabaseManager.CarRentalId = 0;
            DatabaseManager.ActivityTaskId = 0;

            DatabaseManager.Time = flight.DepartureTime;

            _flights.Id = DatabaseManager.FlightId;
            _flights.ConfirmationNumber = flight.ConfirmationNumber;
            _flights.Airline = flight.Airline;
            _flights.FlightNumber = flight.FlightNumber;
            _flights.DepartureDate = flight.DepartureDate;
            _flights.DepartureTime = flight.DepartureTime;
            _flights.DepartureFrom = flight.DepartureFrom;
            _flights.DepartureTerminal = flight.DepartureTerminal;
            _flights.DepartureGate = flight.DepartureGate;
            _flights.ArrivalDate = flight.ArrivalDate;
            _flights.ArrivalTime = flight.ArrivalTime;
            _flights.ArrivalTo = flight.ArrivalTo;
            _flights.ArrivalTerminal = flight.ArrivalTerminal;
            _flights.ArrivalGate = flight.ArrivalGate;
            _flights.Seats = flight.Seats;
            _flights.TripId = flight.TripId;

            var allhumans = _context.Humans.ToList();
            _tfDto.AllHumans = allhumans;

            if (flight == null)
            {
                return NotFound();
            }

            _tfDto.MyFlight = _flights;
            return View(_tfDto);
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ConfirmationNumber,Airline,FlightNumber,DepartureDate,DepartureTime,DepartureFrom,DepartureTerminal,DepartureGate,ArrivalDate,ArrivalTime,ArrivalTo,ArrivalTerminal,ArrivalGate,Seats,TripId")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                int tripId = flight.TripId;
                return RedirectToAction("Details", new { flight.Id });
            }
            return View(flight);

        }



        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.SingleOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ConfirmationNumber,Airline,FlightNumber,DepartureDate,DepartureTime,DepartureFrom,DepartureTerminal,DepartureGate,ArrivalDate,ArrivalTime,ArrivalTo,ArrivalTerminal,ArrivalGate,Seats,TripId")] Flight flight)
        {
            if (id != flight.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { flight.Id });
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .SingleOrDefaultAsync(m => m.Id == id);

            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await _context.Flights.SingleOrDefaultAsync(m => m.Id == id);
            _context.Flights.Remove(flight);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Trips", new { Id = DatabaseManager.TripId });
        }

        private bool FlightExists(int id)
        {
            return _context.Flights.Any(e => e.Id == id);
        }
    }
}

DSEDFinalProjectTripPlanner/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DSEDFinalProjectTripPlanner.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DSEDFinalProjectTripPlanner.Data;
using DSEDFinalProjectTripPlanner.DTO;
using DSEDFinalProjectTripPlanner.Models;
using Microsoft.AspNetCore.Authorization;

namespace DSEDFinalProjectTripPlanner.Controllers
{
    [Authorize]
    public class TripsController : Controller
    {
        private readonly TripContext _context;
        Trip _myTrip = new Trip();

        public TripsController(TripContext context)
        {

            _context = context;
        }

        // GET: Trips
        public async Task<IActionResult> Index()
        {
            return View(await _context.Trips.ToListAsync());
        }

        // GET: Trips/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .SingleOrDefaultAsync(m => m.Id == id);

            TripDTO _tfDto = new TripDTO();
            Trips _trips = new Trips();

            DatabaseManager.TripId = (int)id;
            DatabaseManager.TripStartDate = trip.StartDate;

            _trips.Id = DatabaseManager.TripId;
            _trips.Name = trip.Name;
            _trips.DestinationCity = trip.DestinationCity;
            _trips.DestinationCountry = trip.DestinationCountry;
            _trips.StartDate = trip.StartDate;
            _trips.FinishDate = trip.FinishDate;
            _trips.Description = trip.Description;
            //return _trips;

            _tfDto.AllFlights = _context.Flights.ToList();
            _tfDto.AllLodgings = _context.Lodgings.ToList();
            _tfDto.AllHumans = _context.Humans.ToList();
            _tfDto.AllOtherTransportations = _context.OtherTransportations.ToList();
            _tfDto.AllRestaurants = _context.Restaurants.ToList();
            _tfDto.AllActivities = _context.ActivityTasks.ToList();
            _tfDto.AllCarRentals = _context.CarRentals.ToList();

            var start = trip.StartDate;
            var end = trip.FinishDate;
            var tripdates = new List<DateTime>();
            for (var dt = start; dt <= end; dt = dt.AddDays(1))
            {
                tripdates.Add(dt);
            }
            _tfDto.GetDates = tripdates;

            if (trip == null)
            {
                return NotFound();
            }
            _tfDto.AllTrips = _trips;
            return View(_tfDto);
        }



        // GET: Trips/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DestinationCity,DestinationCountry,StartDate,FinishDate,Description")] Trip trip)
        {

            if (ModelState.IsValid)
            {
                _context.Add(trip);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trip);
        }

        // GET: Trips/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips.SingleOrDefaultAsync(m => m.Id == id);
            if (trip == null)
            {
                return NotFound();
            }
            return View(trip);
        }

        // POST: Trips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DestinationCity,DestinationCountry,StartDate,FinishDate,Description,TripId")] Trip trip)
        {
            if (id != trip.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TripExists(trip.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trip);
        }

        // GET: Trips/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .SingleOrDefaultAsync(m => m.Id == id);

            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trip = await _context.Trips.SingleOrDefaultAsync(m => m.Id == id);
            _context.Trips.Remove(trip);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TripExists(int id)
        {
            return _context.Trips.Any(e => e.Id == id);
        }
    }
}

DSEDFinalProjectTripPlanner/Views/Humans/Create.cshtml
@using DSEDFinalProjectTripPlanner.Database
@model DSEDFinalProjectTripPlanner.Models.Human

@{
    ViewData["Title"] = "Create";
    ViewData["Header"] = "Add Person";

    if (DatabaseManager.TripId != 0)
    {
        if (DatabaseManager.FlightId != 0)
        {
            ViewData["Header"] = "Add Passenger";
            ViewData["FrequentFlyerNumber"] = "Frequent Flyer #";
            ViewData["TicketNumber"] = "Seat #";
        }
        if (DatabaseManager.LodgingId != 0)
        {
            ViewData["Header"] = "Add Guest";
            ViewData["FrequentFlyerNumber"] = "Frequent Guest #";
            ViewData["TicketNumber"] = "Ticket #";
        }
        if (DatabaseManager.OtherTransportationId != 0)
        {
            ViewData["Header"] = "Add Passenger";
            ViewData["FrequentFlyerNumber"] = "Frequent Traveller #";
            ViewData["TicketNumber"] = "Seat #";
        }
        if (DatabaseManager.RestaurantId != 0)
        {
            ViewData["Header"] = "Add Diner";
            ViewData["FrequentFlyerNumber"] = "Loyalty Program #";
            ViewData["TicketNumber"] = "Ticket #";
        }
        if (DatabaseManager.CarRentalId != 0)
        {
            ViewData["Header"] = "Add Driver";
            ViewData["FrequentFlyerNumber"] = "Frequent Renter #";
            ViewData["TicketNumber"] = "Ticket #";
        }
        if (DatabaseManager.ActivityTaskId != 0)
        {
            ViewData["Header"] = "Add Attendee";
            ViewData["FrequentFlyerNumber"] = "Loyalty Program #";
            ViewData["TicketNumber"] = "Ticket #";
        }
    }
    else
    {
        ViewData["Header"] = "Add Persons";
    }

}

<div class="header">
    <h1 style="font-family:cursive; font-size:24px;">@ViewData["Header"]</h1>
</div>
<hr />
@if (DatabaseManager.TripId != 0)
{
    @if (
       DatabaseManager.FlightId != 0 || DatabaseManager.LodgingId != 0 || DatabaseManager.OtherTransportationId != 0 || DatabaseManager.RestaurantId != 0 || DatabaseManager.CarRentalId != 0 || DatabaseManager.ActivityTaskId != 0
       )
    {
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-4">

                        <div class="form-group">
                            <label asp-for="Fullname" class="control-label"></label>
                            <input asp-for="Fullname" class="form-control" />
                            <span asp-validation-for="Fullname" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="FrequentFlyerNumber" class="control-label">@ViewData["FrequentFlyerNumber"]</label>
                            <input asp-for="FrequentFlyerNumber" class="form-control" />
                            <span asp-validation-for="FrequentFlyerNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="TicketNumber" class="control-label">@ViewData["TicketNumber"]</label>
                            <input asp-for="TicketNumber" class="form-control" />
                            <span asp-validation-for="TicketNumber" class="text-danger"></span>
                        </div>
                    </div>


                    @*Ids to be hidden*@
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="TripId" class="control-label"></label>
                            <input asp-for="TripId" class="form-control" readonly="readonly" value="@DatabaseManager.TripId" />
                            <span asp-validation-for="TripId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="FlightId" class="control-label"></label>
                            <input asp-for="FlightId" class="form-control" readonly="readonly" value="@DatabaseManager.FlightId" />
                            <span asp-validation-for="FlightId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="LodgingId" class="control-label"></label>
                            <input asp-for="LodgingId" class="form-control" readonly="readonly" value="@DatabaseManager.LodgingId" />
                            <span asp-validation-for="LodgingId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="OtherTransportationId" class="control-label"></label>
                            <input asp-for="OtherTransportationId" class="form-control" readonly="readonly" value="@DatabaseManager.OtherTransportationId" />
                            <span asp-validation-for="OtherTransportationId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="RestaurantId" class="control-label"></label>
                            <input asp-for="RestaurantId" class="form-control" readonly="readonly" value="@DatabaseManager.RestaurantId" />
                            <span asp-validation-for="RestaurantId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="CarRentalId" class="control-label"></label>
                            <input asp-for="CarRentalId" class="form-control" readonly="readonly" value="@DatabaseManager.CarRentalId" />
                            <span asp-validation-for="CarRentalId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="ActivityTaskId" class="control-label"></label>
                            <input asp-for="ActivityTaskId" class="form-control" readonly="readonly" value="@DatabaseManager.ActivityTaskId" />
                            <span asp-validation-for="ActivityTaskId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="clear"></div>


                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    }
    else
    {
        <p>You can't add a person without selecting a plan</p>
    }
    <div>
        <a asp-area="" asp-controller="Trips" asp-action="Details/@DatabaseManager.TripId" class="btn btn-warning">Back </a>
    </div>
}
else
{
    <p>Please select a trip before adding a persons</p>
    <div>
        <a asp-area="" asp-controller="Trips" asp-action="Index" class="btn-warning">Back</a>
    </div>
}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DSEDFinalProjectTripPlanner/Views/Humans/Delete.cshtml
@using DSEDFinalProjectTripPlanner.Database
@model DSEDFinalProjectTripPlanner.Models.Human

@{
    ViewData["Title"] = "Delete";
}

<h2 style="font-family:cursive; font-size:18px;">Delete</h2>

<h3 style="font-family:cursive; font-size:24px;">Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt>
            Frequent Flyer #
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FrequentFlyerNumber)
        </dd>
        <dt>
            Ticket #
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TicketNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TripId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TripId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LodgingId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LodgingId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OtherTransportationId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OtherTransportationId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RestaurantId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RestaurantId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CarRentalId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarRentalId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActivityTaskId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ActivityTaskId)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-area="" asp-controller="Trips" asp-action="Details/@DatabaseManager.TripId" class="btn btn-warning">Back</a>
    </form>
</div>

DSEDFinalProjectTripPlanner/Views/Humans/Details.cshtml
@using DSEDFinalProjectTripPlanner.Database
@model DSEDFinalProjectTripPlanner.Models.Human

@{
    ViewData["Title"] = "Details";
}

<h2 style="font-family:cursive; font-size:20px;">Details of Persons</h2>

<div>
    <h4 style="font-family:cursive; font-size:24px;">Persons</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TripId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TripId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LodgingId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LodgingId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OtherTransportationId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OtherTransportationId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RestaurantId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RestaurantId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CarRentalId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarRentalId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActivityTaskId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ActivityTaskId)
        </dd>
    </dl>
</div>
<div>
    <p>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-info">Edit</a> |
        <a asp-area="" asp-controller="Flights" asp-action="Details/@DatabaseManager.FlightId" class="btn btn-warning">Back</a>
    </p>
</div>

DSEDFinalProjectTripPlanner/Views/Humans/Index.cshtml
@model IEnumerable<DSEDFinalProjectTripPlanner.Models.Human>

@{ ViewData["Title"] = "Index"; }

<h2 style="font-family:cursive; font-size:24px;">Persons</h2>

<p>
    <a asp-action="Create" class="btn btn-primary">Add Persons Here</a>
</p>
<!-- Table For Display how many persons on Trip-->
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fullname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FrequentFlyerNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TicketNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TripId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LodgingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OtherTransportationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RestaurantId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarRentalId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActivityTaskId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Fullname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FrequentFlyerNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TicketNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TripId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FlightId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LodgingId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OtherTransportationId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RestaurantId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CarRentalId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ActivityTaskId)
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success">Details</a> |
        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
    </td>
</tr>}
    </tbody>
</table>

DSEDFinalProjectTripPlanner/Views/Humans/NumberOfHumans.cshtml
@using DSEDFinalProjectTripPlanner.Database
@model DSEDFinalProjectTripPlanner.Models.Human

@{
    ViewData["Title"] = "Create";
    ViewData["Header"] = "Add Person";
}

<div class="header">
    <h1 style="font-family:cursive; font-size:24px;">@ViewData["Header"]</h1>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="NumberOfHumans">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="control-label">Passengers: </label>

                    <input class="form-control" asp-for="@DatabaseManager.NumOfHumans" type="number" value="1" id="human" />
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Add Passenger" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="" asp-controller="Trips" asp-action="Details/@DatabaseManager.TripId" class="btn btn-warning">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}