DSEDFinalProjectTripPlanner/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace DSEDFinalProjectTripPlanner.Models
{
    public class Flight
    {
        [Required]
        public int Id { get; set; }
        public string ConfirmationNumber { get; set; }
        [Required]
        public string Airline { get; set; }
        [Required]
        public string FlightNumber { get; set; }
        [Required]
        public DateTime DepartureDate { get; set; }
        [Required]
        public DateTime DepartureTime { get; set; }
        [Required]
        public string DepartureFrom { get; set; }
        public string DepartureTerminal { get; set; }
        public string DepartureGate { get; set; }
        [Required]
        public DateTime ArrivalDate { get; set; }
        [Required]
        public DateTime ArrivalTime { get; set; }
        [Required]
        public string ArrivalTo { get; set; }
        public string ArrivalTerminal { get; set; }
        public string ArrivalGate { get; set; }
        public string Seats { get; set; }
        [Required]
        public int TripId { get; set; }

    }
}

DSEDFinalProjectTripPlanner/Controllers/HumansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DSEDFinalProjectTripPlanner.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DSEDFinalProjectTripPlanner.Data;
using DSEDFinalProjectTripPlanner.Models;
using Microsoft.AspNetCore.Authorization;

namespace DSEDFinalProjectTripPlanner.Controllers
{
    [Authorize]
    public class HumansController : Controller
    {
        private readonly Data.TripContext _context;

        public HumansController(Data.TripContext context)
        {
            _context = context;
        }

        public IActionResult NumberOfHumans()
        {
            return View();
        }

        // GET: Humans
        public async Task<IActionResult> Index()
        {
            return View(await _context.Travellers.ToListAsync());
        }

        // GET: Humans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var human = await _context.Travellers
                .SingleOrDefaultAsync(m => m.Id == id);
            if (human == null)
            {
                return NotFound();
            }

            return View(human);
        }

        // GET: Humans/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Humans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fullname, FrequentFlyerNumber,TicketNumber,TripId,FlightId,LodgingId,OtherTransportationId,RestaurantId,CarRentalId,ActivityTaskId")] Human human)
        {
            if (ModelState.IsValid)
            {
                _context.Add(human);
                await _context.SaveChangesAsync();

                if (DatabaseManager.FlightId != 0)
                {
                    return RedirectToAction("Details", "Flights", new { Id = human.FlightId });
                }
                if (DatabaseManager.LodgingId != 0)
                {
                    return RedirectToAction("Details", "Lodgings", new { Id = human.LodgingId });
                }
                if (DatabaseManager.OtherTransportationId != 0)
                {
                    return RedirectToAction("Details", "OtherTransportations", new { Id = human.OtherTransportationId });
                }
                if (DatabaseManager.RestaurantId != 0)
                {
                    return RedirectToAction("Details", "Restaurants", new { Id = human.RestaurantId });
                }
                if (DatabaseManager.CarRentalId != 0)
                {
                    return RedirectToAction("Details", "CarRentals", new { Id = human.CarRentalId });
                }
                if (DatabaseManager.ActivityTaskId != 0)
                {
                    return RedirectToAction("Details", "ActivityTasks", new { Id = human.ActivityTaskId });
                }


            }
            return View(human);
        }

        // GET: Humans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var human = await _context.Travellers.SingleOrDefaultAsync(m => m.Id == id);
            if (human == null)
            {
                return NotFound();
            }
            return View(human);
        }

        // POST: Humans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fullname, FrequentFlyerNumber,TicketNumber,TripId,FlightId,LodgingId,OtherTransportationId,RestaurantId,CarRentalId,ActivityTaskId")] Human human)
        {
            if (id != human.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(human);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HumanExists(human.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (DatabaseManager.FlightId != 0)
                {
                    return RedirectToAction("Details", "Flights", new { Id = human.FlightId });
                }
                if (DatabaseManager.LodgingId != 0)
                {
                    return RedirectToAction("Details", "Lodgings", new { Id = human.LodgingId });
                }
                if (DatabaseManager.OtherTransportationId != 0)
                {
                    return RedirectToAction("Details", "OtherTransportations", new { Id = human.OtherTransportationId });
                }
                if (DatabaseManager.RestaurantId != 0)
                {
                    return RedirectToAction("Details", "Restaurants", new { Id = human.RestaurantId });
                }
                if (DatabaseManager.CarRentalId != 0)
                {
                    return RedirectToAction("Details", "CarRentals", new { Id = human.CarRentalId });
                }
                if (DatabaseManager.ActivityTaskId != 0)
                {
                    return RedirectToAction("Details", "ActivityTasks", new { Id = human.ActivityTaskId });
                }
            }
            return View(human);
        }

        // GET: Humans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var human = await _context.Travellers
                .SingleOrDefaultAsync(m => m.Id == id);
            if (human == null)
            {
                return NotFound();
            }

            return View(human);
        }

        // POST: Humans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var human = await _context.Travellers.SingleOrDefaultAsync(m => m.Id == id);
            _context.Travellers.Remove(human);
            await _context.SaveChangesAsync();


            if (DatabaseManager.FlightId != 0)
            {
                return RedirectToAction("Details", "Flights", new { Id = human.FlightId });
            }
            if (DatabaseManager.LodgingId != 0)
            {
                return RedirectToAction("Details", "Lodgings", new { Id = human.LodgingId });
            }
            if (DatabaseManager.OtherTransportationId != 0)
            {
                return RedirectToAction("Details", "OtherTransportations", new { Id = human.OtherTransportationId });
            }
            if (DatabaseManager.RestaurantId != 0)
            {
                return RedirectToAction("Details", "Restaurants", new { Id = human.RestaurantId });
            }
            if (DatabaseManager.CarRentalId != 0)
            {
                return RedirectToAction("Details", "CarRentals", new { Id = human.CarRentalId });
            }
            if (DatabaseManager.ActivityTaskId != 0)
            {
                return RedirectToAction("Details", "ActivityTasks", new { Id = human.ActivityTaskId });
            }
            return RedirectToAction("Details", "Trips", new { Id = DatabaseManager.TripId });
        }

        private bool HumanExists(int id)
        {
            return _context.Travellers.Any(e => e.Id == id);
        }
    }
}

DSEDFinalProjectTripPlanner/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DSEDFinalProjectTripPlanner.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DSEDFinalProjectTripPlanner.Data;
using DSEDFinalProjectTripPlanner.DTO;
using DSEDFinalProjectTripPlanner.Models;
using Microsoft.AspNetCore.Authorization;

namespace DSEDFinalProjectTripPlanner.Controllers
{
    [Authorize]
    public class TripsController : Controller
    {
        private readonly TripContext _context;
        Trip _myTrip = new Trip();

        public TripsController(TripContext context)
        {

            _context = context;
        }

        // GET: Trips
        public async Task<IActionResult> Index()
        {
            return View(await _context.Trips.ToListAsync());
        }

        // GET: Trips/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .SingleOrDefaultAsync(m => m.Id == id);

            TripDTO _tfDto = new TripDTO();
            Trips _trips = new Trips();

            DatabaseManager.TripId = (int)id;
            DatabaseManager.TripStartDate = trip.StartDate;

            _trips.Id = DatabaseManager.TripId;
            _trips.Name = trip.Name;
            _trips.DestinationCity = trip.DestinationCity;
            _trips.DestinationCountry = trip.DestinationCountry;
            _trips.StartDate = trip.StartDate;
            _trips.FinishDate = trip.FinishDate;
            _trips.Description = trip.Description;
            //return _trips;

            _tfDto.AllFlights = _context.Flights.ToList();
            _tfDto.AllLodgings = _context.Lodgings.ToList();
            _tfDto.AllHumans = _context.Humans.ToList();
            _tfDto.AllOtherTransportations = _context.OtherTransportations.ToList();
            _tfDto.AllRestaurants = _context.Restaurants.ToList();
            _tfDto.AllActivities = _context.ActivityTasks.ToList();
            _tfDto.AllCarRentals = _context.CarRentals.ToList();

            var start = trip.StartDate;
            var end = trip.FinishDate;
            var tripdates = new List<DateTime>();
            for (var dt = start; dt <= end; dt = dt.AddDays(1))
            {
                tripdates.Add(dt);
            }
            _tfDto.GetDates = tripdates;

            if (trip == null)
            {
                return NotFound();
            }
            _tfDto.AllTrips = _trips;
            return View(_tfDto);
        }



        // GET: Trips/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DestinationCity,DestinationCountry,StartDate,FinishDate,Description")] Trip trip)
        {

            if (ModelState.IsValid)
            {
                _context.Add(trip);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trip);
        }

        // GET: Trips/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips.SingleOrDefaultAsync(m => m.Id == id);
            if (trip == null)
            {
                return NotFound();
            }
            return View(trip);
        }

        // POST: Trips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DestinationCity,DestinationCountry,StartDate,FinishDate,Description,TripId")] Trip trip)
        {
            if (id != trip.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TripExists(trip.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trip);
        }

        // GET: Trips/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .SingleOrDefaultAsync(m => m.Id == id);

            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trip = await _context.Trips.SingleOrDefaultAsync(m => m.Id == id);
            _context.Trips.Remove(trip);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TripExists(int id)
        {
            return _context.Trips.Any(e => e.Id == id);
        }
    }
}

DSEDFinalProjectTripPlanner/Views/Flights/Create.cshtml
@using DSEDFinalProjectTripPlanner.Database
@model DSEDFinalProjectTripPlanner.Models.Flight

@{
    ViewData["Title"] = "Create";
    ViewData["Header"] = "Add a new Flight";
}

<div class="header">
    <h1 style="font-family:cursive; font-size:24px;">@ViewData["Header"]</h1>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" >
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ConfirmationNumber" class="control-label">Confirmation Number</label>
                    <input asp-for="ConfirmationNumber" class="form-control" />
                    <span asp-validation-for="ConfirmationNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Airline" class="control-label">Airline <span class="required">*</span></label>
                    <input asp-for="Airline" class="form-control" />
                    <span asp-validation-for="Airline" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="FlightNumber" class="control-label">Flight # <span class="required">*</span></label>
                    <input asp-for="FlightNumber" class="form-control" />
                    <span asp-validation-for="FlightNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Seats" class="control-label"></label>
                    <input asp-for="Seats" class="form-control" />
                    <span asp-validation-for="Seats" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12">
                <label class="control-label">Departure</label>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="DepartureFrom" class="control-label">From (city or airport) <span class="required">*</span></label>
                    <input asp-for="DepartureFrom" class="form-control" />
                    <span asp-validation-for="DepartureFrom" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="DepartureTerminal" class="control-label">Terminal</label>
                    <input asp-for="DepartureTerminal" class="form-control" />
                    <span asp-validation-for="DepartureTerminal" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="DepartureGate" class="control-label">Gate</label>
                    <input asp-for="DepartureGate" class="form-control" />
                    <span asp-validation-for="DepartureGate" class="text-danger"></span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="DepartureDate" class="control-label">Departure Date <span class="required">*</span></label>
                    <input asp-for="DepartureDate" type="date" value="@DatabaseManager.TripStartDate" class="form-control" />
                    <span asp-validation-for="DepartureDate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="DepartureTime" class="control-label">Departure Time <span class="required">*</span></label>
                    <input asp-for="DepartureTime" type="time" datetime="HH:ss" class="form-control" />
                    <span asp-validation-for="DepartureTime" class="text-danger"></span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="col-md-12">
                <label class="control-label">Arrival</label>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ArrivalTo" class="control-label">To (city or airport) <span class="required">*</span></label>
                    <input asp-for="ArrivalTo" class="form-control" />
                    <span asp-validation-for="ArrivalTo" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ArrivalTerminal" class="control-label">Terminal</label>
                    <input asp-for="ArrivalTerminal" class="form-control" />
                    <span asp-validation-for="ArrivalTerminal" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ArrivalGate" class="control-label">Gate</label>
                    <input asp-for="ArrivalGate" class="form-control" />
                    <span asp-validation-for="ArrivalGate" class="text-danger"></span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ArrivalDate" class="control-label">Arrival Date <span class="required">*</span></label>
                    <input asp-for="ArrivalDate" type="date" class="form-control" />
                    <span asp-validation-for="ArrivalDate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ArrivalTime" class="control-label">Arrival Time <span class="required">*</span></label>
                    <input asp-for="ArrivalTime" type="time" class="form-control" />
                    <span asp-validation-for="ArrivalTime" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    @*id="hidden""*@
                    <label asp-for="TripId" class="control-label"></label>
                    <input asp-for="TripId" class="form-control" readonly="readonly" value="@DatabaseManager.TripId" />
                    <span asp-validation-for="TripId" class="text-danger"></span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="col-md-12">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <span class="required">* Required</span>
                </div>
            </div>




        </form>
    </div>

</div>

<div>
    <a asp-action="Index" class="btn btn-warning">Back </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DSEDFinalProjectTripPlanner/Views/Flights/Delete.cshtml
@using DSEDFinalProjectTripPlanner.Database
@model DSEDFinalProjectTripPlanner.Models.Flight

@{
    ViewData["Title"] = "Delete";
}

<h2 style="font-family:cursive; font-size:18px;">Delete</h2>

<h3 style="font-family:cursive; font-size:24px;">Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConfirmationNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ConfirmationNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Airline)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Airline)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FlightNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FlightNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureFrom)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureFrom)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureTerminal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureTerminal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureGate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureGate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalTo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTerminal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalTerminal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalGate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalGate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Seats)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Seats)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-area="" asp-controller="Trips" asp-action="Details/@DatabaseManager.TripId" class="btn btn-warning">Back</a>
    </form>
</div>

DSEDFinalProjectTripPlanner/Views/Flights/Details.cshtml
@using DSEDFinalProjectTripPlanner.Database
@model DSEDFinalProjectTripPlanner.DTO.TripDTO

@{
    ViewData["Title"] = "Details";
    ViewData["Header"] = "Flights Details are Here";
}

<div class="header">
    <h1 style="font-family:cursive; font-size:24px;">@ViewData["Header"]</h1>
</div>
<hr />

<div class="col-md-12">
    <div class="col-md-12">
        <div class="col-md-12">
            <div class="details">
                <h5>
                    @DatabaseManager.DepartureDate(Model.MyFlight.DepartureDate)
                </h5>
                <h4>
                    @Html.DisplayFor(model => model.MyFlight.DepartureFrom) to
                    @Html.DisplayFor(model => model.MyFlight.ArrivalTo) |
                    @Html.DisplayFor(model => model.MyFlight.Airline)
                    @Html.DisplayFor(model => model.MyFlight.FlightNumber)
                </h4>
                <p>
                    Confirmation Number: @Html.DisplayFor(model => model.MyFlight.ConfirmationNumber)
                </p>
            </div>
        </div>

        <div class="col-md-12">
            <div class="Departure">
                <div class="col-md-12">
                    <label>Depart:</label>
                </div>

                <div class="col-md-2">
                    <p>
                        @DatabaseManager.DepartureTime(Model.MyFlight.DepartureTime)
                    </p>
                </div>
                <div class="col-md-4">
                    <p>
                        @Html.DisplayFor(model => model.MyFlight.DepartureFrom)
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        Terminal: @Html.DisplayFor(model => model.MyFlight.DepartureTerminal)
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        Gate: @Html.DisplayFor(model => model.MyFlight.DepartureGate)
                    </p>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="col-md-12">
            <div class="Arrival">
                <div class="col-md-12">
                    <label>Arrive:</label>
                </div>

                <div class="col-md-2">
                    <p>
                        @DatabaseManager.DepartureTime(Model.MyFlight.ArrivalTime)
                    </p>
                </div>
                <div class="col-md-4">
                    <p>
                        @Html.DisplayFor(model => model.MyFlight.ArrivalTo)
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        Terminal: @Html.DisplayFor(model => model.MyFlight.ArrivalTerminal)
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        Gate: @Html.DisplayFor(model => model.MyFlight.ArrivalGate)
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="Duration">
                <div class="col-md-2">

                </div>
               
                <div class="col-md-3">
                    <p>
                        Seats: @Html.DisplayFor(model => model.MyFlight.Seats)
                    </p>
                </div>
            </div>
        </div>

        <div class="passengers">
            <h4>Who's Going?</h4>
            @foreach (var human in Model.AllHumans.OrderBy(human => human.TicketNumber).ThenBy(human => human.Id))
            {
                if (human.TripId == DatabaseManager.TripId && human.FlightId == DatabaseManager.FlightId)
                {
                    <div class="col-md-12">
                        <div class="col-md-3">
                            <p>@Html.DisplayFor(modelItem => human.Fullname)</p>
                        </div>
                        <div class="col-md-3">
                            <p>Frequent Flyer #: @Html.DisplayFor(modelItem => human.FrequentFlyerNumber)</p>
                        </div>
                        <div class="col-md-3">
                            <p>
                                Seat #: @Html.DisplayFor(modelItem => human.TicketNumber)
                            </p>
                        </div>
                        <div class="col-md-3">
                            <p>
                                <a asp-controller="Humans" asp-action="Edit" asp-route-id="@human.Id">Edit</a> |
                                <a asp-controller="Humans" asp-action="Delete" asp-route-id="@human.Id">Delete</a>
                            </p>
                        </div>
                    </div>
                }

            }
        </div>
    </div>
</div>

<div>
    <p>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-info">Edit</a> |
        <a asp-area="" asp-controller="Humans" asp-action="Create" class="btn btn-success">Add Passenger</a> |
        <a asp-area="" asp-controller="Trips" asp-action="Details/@DatabaseManager.TripId" class="btn btn-warning">
            Back 
        </a>

    </p>
</div>